apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eck
spec:
  version: 7.12.1
  count: 1
  elasticsearchRef:
    name: eck
  http:
    tls:
      selfSignedCertificate:
        disabled: true